### ISSUE TITLE
Plugin load failed

### ISSUE THREAD

**Issue by prajaybasu** [ele828/hexo-medium-image-plugin#1]
After hexo clean : 

```
ERROR Plugin load failed: hexo-medium-image-plugin
SyntaxError: Unexpected token [
    at Object.exports.runInThisContext (vm.js:53:16)
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\lib\hexo\index.js:227:17
    at tryCatcher (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:630:18)
    at Promise._resolveCallback (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:425:57)
    at Promise._settlePromiseFromHandler (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:516:17)
    at Promise._settlePromise (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:630:18)
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\nodeback.js:42:21
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\hexo-fs\node_modules\graceful-fs\graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
INFO  Deleted database.
INFO  Deleted public folder.
```

hexo 3.2.2

If it is due to another plugin, then I am sorry - I am currently figuring out what is the issue.

**Comment by ele828** [comment]
It seems like something wrong with bluebird library. Could you please upgrade your Node to v6.2.1 or higher? And then, see what's going on.

**Comment by prajaybasu** [comment]
Node 6.2.2 (I did npm install after upgrading from 5.5.0, is that ok ?) . 

```
ERROR Plugin load failed: hexo-medium-image-plugin
Error: Cannot find module 'hexo-log'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\lib\hexo\index.js:213:21)
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo-medium-image-plugin\index.js:7:16
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\lib\hexo\index.js:229:12
    at tryCatcher (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:630:18)
    at Promise._resolveCallback (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:425:57)
    at Promise._settlePromiseFromHandler (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:516:17)
    at Promise._settlePromise (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:630:18)
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\nodeback.js:42:21
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\hexo-fs\node_modules\graceful-fs\graceful-fs.js:78:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

With node 6 there is a new issue (hexo-log), I will look up hexo issues later..

**Comment by ele828** [comment]
@prajaybasu  Yep, that's fine. I just fixed the hexo-log bug (because I forget to define it in package.json). And you should probably re-install it.

```
npm i hexo-medium-image-plugin --save
```

Hope it works!

**Comment by prajaybasu** [comment]
The plugin loads now, however I get these errors and nothing is generated : 

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'image_path' of undefined
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo-medium-image-plugin\index.js:197:51
    at next (native)
    at onFulfilled (C:\Users\Prajay\Documents\GitHub\blog\node_modules\co\index.js:65:19)
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\co\index.js:54:5
    at co (C:\Users\Prajay\Documents\GitHub\blog\node_modules\co\index.js:50:10)
    at Hexo.mediumImagePlugin (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo-medium-image-plugin\index.js:195:37)
    at Hexo.tryCatcher (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\lib\extend\filter.js:68:35
    at tryCatcher (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\reduce.js:145:18)
    at Object.gotAccum (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\reduce.js:134:25)
    at Object.tryCatcher (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
INFO  Finished including all critical css into the html files
FATAL Cannot read property 'image_path' of undefined
TypeError: Cannot read property 'image_path' of undefined
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo-medium-image-plugin\index.js:197:51
    at next (native)
    at onFulfilled (C:\Users\Prajay\Documents\GitHub\blog\node_modules\co\index.js:65:19)
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\co\index.js:54:5
    at co (C:\Users\Prajay\Documents\GitHub\blog\node_modules\co\index.js:50:10)
    at Hexo.mediumImagePlugin (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo-medium-image-plugin\index.js:195:37)
    at Hexo.tryCatcher (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\lib\extend\filter.js:68:35
    at tryCatcher (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\reduce.js:145:18)
    at Object.gotAccum (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\reduce.js:134:25)
    at Object.tryCatcher (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Prajay\Documents\GitHub\blog\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by ele828** [comment]
@prajaybasu , You should specify configuration in `_config.yml` file like following (see README.md):

``` yaml
medium_image_plugin:
    image_path: 'img'
    max_width: 680
```

`image_path` means where your images stored.  `max_width` means the maximum of page width.
